backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "stories"
    label: "Stories"
    folder: "stories"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Contributor"
        name: "contributor"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
